from __future__ import annotations

import json

import streamlit as st

from app.ui.components import render_bullet_card, render_hero_panel, render_info_card, render_kpi_grid, render_section_header
from app.ui.theme import inject_theme
from config.settings import get_settings
from core.pipeline import build_portfolio_snapshot


def main() -> None:
    settings = get_settings()
    st.set_page_config(
        page_title="Samuel Maia Analytics Platform",
        page_icon="SM",
        layout="wide",
    )
    inject_theme()

    snapshot = build_portfolio_snapshot(settings)
    executive_summary = snapshot["genai_outputs"]["executive_summary"]
    change_drivers = snapshot["change_drivers"]
    quality_report = snapshot["quality_report"]

    st.sidebar.title("Review Lens")
    st.sidebar.caption("Use this app as an executive, technical, and governance review surface.")
    st.sidebar.markdown(
        """
        - `Executive Overview`: portfolio readiness and change movement
        - `Governance and Quality`: policy, LGPD, quality, and catalog surfaces
        - `Semantic Metrics`: KPI definitions and domain scores
        - `Repository Intelligence`: asset readiness and historical comparisons
        - `GenAI Analytics Assistant`: narrative drafts and metric explanations
        - `Change Drivers`: what changed and recommended action
        """
    )

    render_hero_panel(
        "Analytics Portfolio Platform",
        "Executive-grade review surface for analytics engineering, governed outputs, semantic metrics, and business-facing delivery.",
        "Portfolio Control Tower",
        chips=[
            f"Environment: {settings.env.upper()}",
            f"Quality Pass Rate: {quality_report['pass_rate']:.1f}%",
            f"Projects: {len(snapshot['repository_registry'])}",
        ],
    )

    render_section_header(
        "Executive Snapshot",
        "Operationally structured view of portfolio metrics, quality signals, and AI-assisted commentary.",
    )
    render_kpi_grid(snapshot["semantic_metrics"])

    overview_col, action_col = st.columns((1.15, 0.85))
    with overview_col:
        render_info_card("Executive Summary", executive_summary["narrative"])
        render_bullet_card("Executive Signals", executive_summary["bullets"])
    with action_col:
        render_info_card("Recommended Action", change_drivers.get("recommended_action", ""))
        render_bullet_card(
            "Why This Matters",
            [
                "Trust and quality signals are visible before stakeholders consume the output.",
                "The same KPI logic is reused across app, API, warehouse, and contracts.",
                "Change movement is summarized instead of hidden in implementation detail.",
            ],
        )

    tab1, tab2, tab3, tab4 = st.tabs(
        ["Operating Surface", "Quality and Governance", "GenAI Insights", "Observability"]
    )

    with tab1:
        render_section_header("Repository Registry", "Selective integration of local reference repositories.")
        st.dataframe(snapshot["repository_registry"], width="stretch", hide_index=True)
        st.caption(change_drivers.get("summary", ""))
        if change_drivers.get("drivers"):
            st.dataframe(change_drivers["drivers"], width="stretch", hide_index=True)

    with tab2:
        render_section_header("Data Quality", "Current governed checks for the sample analytical surface.")
        quality_left, quality_right = st.columns((0.8, 1.2))
        with quality_left:
            st.metric("Checks", f"{quality_report['total_checks']}")
            st.metric("Passed", f"{quality_report['passed_checks']}")
            st.metric("Pass Rate", f"{quality_report['pass_rate']:.1f}%")
        with quality_right:
            st.dataframe(quality_report["results"], width="stretch", hide_index=True)
        render_section_header("Semantic Metrics Catalog", "Definitions and domain rollups used by the platform.")
        st.json(snapshot["metric_catalog"])

    with tab3:
        render_section_header("GenAI Insight Layer", "Analytics-oriented drafts generated by a provider-agnostic service.")
        st.markdown(snapshot["genai_insight"]["narrative"])
        st.caption(f"Provider status: {snapshot['genai_insight']['provider_status']}")
        st.dataframe(
            [
                {
                    "use_case": artifact["use_case"],
                    "generation_mode": artifact["generation_mode"],
                    "provider_status": artifact["provider_status"],
                    "prompt_reference": artifact["prompt_reference"],
                }
                for artifact in snapshot["genai_outputs"].values()
            ],
            width="stretch",
            hide_index=True,
        )

    with tab4:
        render_section_header("Observability Event", "Latest structured event emitted by the pipeline.")
        st.code(json.dumps(snapshot["observability_event"], indent=2), language="json")
        recent_events = snapshot["operational_context"].get("recent_events", [])
        if recent_events:
            st.subheader("Recent Runtime Events")
            st.dataframe(recent_events, width="stretch", hide_index=True)


if __name__ == "__main__":
    main()
